language: python

dist: bionic

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gfortran
  - gfortran --version
  - python --version
  - python -m pip install numpy
  # - python -m pip install camb

install:
  - python -m pip install .

script:
  # - python -m unittest mflike.tests.test_mflike
